<?php

declare(strict_types=1);

use Modules\Core\Public\Support\PatternScan;

/** @return list<string> the scripts that patch the generated native project */
function scaffoldPatchScripts(): array
{
    return [
        'nativephp_android_adaptive_icon.php',
        'nativephp_android_file_chooser.php',
        'nativephp_brand_boot_splash.php',
        'nativephp_exclude_data_from_backup.php',
        'nativephp_extend_bundle_copy_timeout.php',
        'nativephp_grant_webview_camera.php',
        'nativephp_ios_app_icon.php',
        'nativephp_ios_download_delegate.php',
        'nativephp_ios_request_body_stream.php',
        'nativephp_keep_webview_cookies.php',
        'nativephp_theme_native_shell.php',
    ];
}

function scaffoldScriptsDirectory(): string
{
    // Probed by the file, not the directory: the mobile-app composer root has
    // a scripts/ of its own carrying two shell scripts and none of these, so
    // is_dir() answered yes and every read then failed.
    foreach ([base_path('scripts'), base_path('../scripts')] as $candidate) {
        if (is_file($candidate.DIRECTORY_SEPARATOR.'nativephp_scaffold_root.php')) {
            return $candidate;
        }
    }

    return base_path('scripts');
}

// The patch scripts resolved the generated project as ../mobile-app/nativephp/,
// which exists in this repository and nowhere else. In a materialized mobile-build
// tree the scripts and the scaffold share one root, so each printed "no scaffold
// yet" and exited 0: a green build carrying NativePHP's own icon.

it('resolves no scaffold path by hand any more', function (): void {
    $hardcoded = [];
    $unprobed = [];

    foreach (scaffoldPatchScripts() as $script) {
        $path = scaffoldScriptsDirectory().DIRECTORY_SEPARATOR.$script;
        $source = (string) file_get_contents($path);

        // Either literal is what pinned them to this repository's layout.
        if (str_contains($source, '/../mobile-app/nativephp/')
            || str_contains($source, '/mobile-app/nativephp/')
            || str_contains($source, '/../mobile-app/vendor/')) {
            $hardcoded[] = $script;
        }

        if (! str_contains($source, 'beatraxScaffoldPath(')
            && ! str_contains($source, 'beatraxMobileVendorPath(')) {
            $unprobed[] = $script;
        }
    }

    expect($hardcoded)->toBe([], 'still pinned to ../mobile-app/: '.implode(', ', $hardcoded))
        ->and($unprobed)->toBe([], 'does not probe for the scaffold: '.implode(', ', $unprobed));
});

it('finds the scaffold in either tree shape', function (): void {
    require_once scaffoldScriptsDirectory().DIRECTORY_SEPARATOR.'nativephp_scaffold_root.php';

    $base = sys_get_temp_dir().'/beatrax-scaffold-'.bin2hex(random_bytes(6));

    // The materialized shape: scripts and scaffold under one root.
    mkdir($base.'/nativephp/android/app/src/main', 0o777, true);
    file_put_contents($base.'/nativephp/android/app/src/main/AndroidManifest.xml', '<manifest/>');

    putenv('BEATRAX_NATIVE_ROOT='.$base);

    try {
        expect(beatraxScaffoldPath('android/app/src/main'))
            ->toBe($base.'/nativephp/android/app/src/main');

        // A path that is not there is still null, so the skip stays a skip.
        expect(beatraxScaffoldPath('ios/NativePHP/NotHere.swift'))->toBeNull();
    } finally {
        putenv('BEATRAX_NATIVE_ROOT');
    }
});

it('still finds this repository own scaffold', function (): void {
    require_once scaffoldScriptsDirectory().DIRECTORY_SEPARATOR.'nativephp_scaffold_root.php';

    // mobile-app/nativephp is generated by native:install and gitignored, so a
    // clean checkout has none — which is the case the skip exists for, and a
    // null here is the right answer rather than a failure.
    if (! is_dir(base_path('mobile-app/nativephp')) && ! is_dir(base_path('../mobile-app/nativephp'))) {
        expect(beatraxScaffoldPath('android/app/src/main'))->toBeNull();

        return;
    }

    $resolved = beatraxScaffoldPath('android/app/src/main');

    expect($resolved)->toBeString()
        ->and(is_file($resolved.'/AndroidManifest.xml'))->toBeTrue();
});

// A patch script that resolves two independent targets — a generated scaffold
// file and a vendor source, or one platform and the other — must not let the
// first one's absence end the process. `nativephp_grant_webview_camera.php`
// did, and the half it skipped was the vendor patch, the only one that
// survives a rebuild; `nativephp_exclude_data_from_backup.php` did, and the
// half it skipped was the iCloud exclusion for the whole ledger. Both reported
// success in a line naming the other platform.
it('ends a missing-target skip at its own half rather than the whole run', function (): void {
    $scripts = glob(scaffoldScriptsDirectory().DIRECTORY_SEPARATOR.'nativephp_*.php') ?: [];

    // Counted first: a resolver that found nothing would otherwise report a
    // clean tree, which is the same silence this rule exists to catch.
    expect($scripts)->not->toBeEmpty();

    $offenders = [];
    $examined = 0;

    foreach ($scripts as $path) {
        $lines = explode("\n", (string) file_get_contents($path));

        $targets = [];
        $exits = [];

        foreach ($lines as $number => $line) {
            $resolved = PatternScan::first("/beatrax(?:ScaffoldPath|MobileVendorPath)\\(\s*'([^']+)'/", $line);

            if ($resolved !== []) {
                $targets[] = [$number, $resolved[1]];
            }

            if (PatternScan::matches('/^\s*exit\(0\);/', $line)) {
                $exits[] = $number;
            }
        }

        $first = $targets[0] ?? null;
        $later = array_values(array_filter($targets, fn (array $t): bool => $first !== null && $t[1] !== $first[1]));

        if ($first === null || $later === []) {
            continue;
        }

        $examined++;

        foreach ($exits as $exit) {
            if ($exit > $first[0] && $exit < $later[0][0]) {
                $offenders[] = basename($path).':'.($exit + 1);

                break;
            }
        }
    }

    expect($examined)->toBeGreaterThan(1)
        ->and($offenders)->toBe([], implode("\n  ", array_merge(
            ['A skip guarding one target must end that half, not the process.',
                'These scripts exit(0) between resolving one target and resolving a different one,',
                'so the later half is silently skipped whenever the earlier one is absent:'],
            $offenders,
        )));
});

/**
 * @return array<string, string> patch scripts deliberately in no build chain,
 *                               each mapped to why
 */
function scaffoldScriptsInNoChain(): array
{
    return [
        // Superseded by nativephp_developer_id_signing.php, which pins an
        // explicit mac.identity. Kept for local unsigned development builds
        // and recorded as such in .docs/features/desktop/build-prebuild-hooks.md.
        'nativephp_force_adhoc_signing' => 'kept for local unsigned development builds',
    ];
}

// A script that is on disk and in no chain never runs, and nothing says so:
// the build is green, the patch simply is not applied, and what ships differs
// from what the repository appears to do. The list->disk direction was already
// checked; this is disk->list, which is the direction a newly added script
// goes missing in.
it('runs every patch script from some chain, or names why it does not', function (): void {
    $directory = scaffoldScriptsDirectory();

    $onDisk = array_map(
        static fn (string $path): string => basename($path, '.php'),
        glob($directory.DIRECTORY_SEPARATOR.'nativephp_*.php') ?: [],
    );

    // Counted before anything is subtracted, so a resolver that found no
    // scripts cannot report a fully covered tree.
    expect($onDisk)->toHaveCount(count($onDisk))->and($onDisk)->not->toBeEmpty();

    // Read as text, not executed: config/nativephp.php calls env() and the
    // runner is a script with side effects, so enumerating them by running
    // them would invoke the build behaviour under test.
    $invoked = [];

    foreach ([$directory.'/nativephp_patch_all.php', dirname($directory).'/config/nativephp.php'] as $chain) {
        if (! is_file($chain)) {
            continue;
        }

        foreach (PatternScan::all('/nativephp_[a-z0-9_]+/', (string) file_get_contents($chain))[0] as $name) {
            $invoked[$name] = true;
        }
    }

    expect($invoked)->not->toBeEmpty();

    // Neither is a patch: one is the runner, the other the shared resolver.
    $notPatches = ['nativephp_patch_all', 'nativephp_scaffold_root'];
    $pinned = scaffoldScriptsInNoChain();

    $orphans = array_values(array_filter(
        $onDisk,
        static fn (string $name): bool => ! isset($invoked[$name])
            && ! in_array($name, $notPatches, true)
            && ! array_key_exists($name, $pinned),
    ));

    // A pin that no longer names an uninvoked script is the same silence one
    // level up, so it fails too rather than rotting into a name nobody checks.
    $stale = array_values(array_filter(
        array_keys($pinned),
        static fn (string $name): bool => ! in_array($name, $onDisk, true) || isset($invoked[$name]),
    ));

    expect($orphans)->toBe([], 'in no build chain and unexplained: '.implode(', ', $orphans))
        ->and($stale)->toBe([], 'pinned as unchained but now absent or invoked: '.implode(', ', $stale));
});
