{{--
    Privacy pill — the single emerald-dot footer line that reads
    "● Your data stays on this computer". One per wizard page; sits in
    the wizard footer.

    The emerald dot is generated by `.privacy-pill::before` in app.css
    (not an emoji) so the dot remains crisp at any zoom level and
    inherits the theme's emerald token without a separate inline color
    declaration.
--}}
@props([
    'label' => 'Your data stays on this computer',
])

<span {{ $attributes->class(['privacy-pill']) }} aria-label="{{ $label }}">
    {{ $label }}
</span>
