<?php

declare(strict_types=1);

return [
    'title' => 'Tax Export :year',

    'year_label' => 'Year:',
    'total_items_label' => 'Total items:',
    'total_deductions_label' => 'Total deductions:',
    'total_income_label' => 'Total income:',

    'empty' => 'No tax-tagged transactions for :year.',
    'uncategorised' => 'Uncategorised',

    'col_date' => 'Date',
    'col_counterparty' => 'Counterparty',
    'col_description' => 'Description',
    'col_note' => 'Note',
    'col_amount' => 'Amount (EUR)',

    'subtotal' => 'Subtotal',

    'footer' => 'Generated by beatrax — local-only personal finance — :year',
];
