<?php

declare(strict_types=1);

namespace Modules\Sync\Public\Events;

/**
 * Dispatched for every user-driven mutation to an envelope_settings row.
 *
 * Mirrors TransactionSplitMutated's contract but targets the per-envelope
 * overspend-mode settings table (D-25). SyncCaptureListener's handlers
 * hard-code the target table name per event type, so this dedicated event
 * exists to avoid silently mis-capturing a settings mutation as a
 * `transactions` op-log row.
 *
 * `settingId` is the stable `envelope_settings.id` primary key — set once via
 * updateOrCreate() and never regenerated by an edit, so per-(table, pk,
 * field) LWW merge converges correctly across devices.
 *
 * Synchronous dispatch — does NOT implement ShouldQueue.
 */
final readonly class EnvelopeSettingMutated
{
    /**
     * @param  string  $mutationType  'create' | 'edit' | 'delete'
     * @param  array<string, mixed>  $dirtyFields  Changed field => new-value map.
     *                                             Empty for delete ops.
     */
    public function __construct(
        public int $settingId,
        public int $userId,
        public string $mutationType,
        public array $dirtyFields = [],
    ) {}
}
