<?php

declare(strict_types=1);

namespace Modules\Sync\Public\Events;

/**
 * Dispatched for every user-driven mutation to an envelope_assignments row.
 *
 * Mirrors TransactionSplitMutated's contract but targets the envelope
 * assignment table (D-25). SyncCaptureListener's handlers hard-code the
 * target table name per event type, so this dedicated event exists to avoid
 * silently mis-capturing an assignment mutation as a `transactions` op-log
 * row — the same 13.1 D-12a lesson that split off TransactionSplitMutated
 * from TransactionMutated.
 *
 * `assignmentId` is the stable `envelope_assignments.id` primary key — set
 * once via updateOrCreate() (D-01/D-06) and never regenerated by an edit, so
 * per-(table, pk, field) LWW merge converges correctly across devices.
 *
 * Synchronous dispatch — does NOT implement ShouldQueue.
 */
final readonly class EnvelopeAssignmentMutated
{
    /**
     * @param  string  $mutationType  'create' | 'edit' | 'delete'
     * @param  array<string, mixed>  $dirtyFields  Changed field => new-value map.
     *                                             Empty for delete ops.
     */
    public function __construct(
        public int $assignmentId,
        public int $userId,
        public string $mutationType,
        public array $dirtyFields = [],
    ) {}
}
