<?php

declare(strict_types=1);

namespace Modules\Desktop\Internal\Listeners;

use Modules\Desktop\Public\Events\NotificationDeepLink;
use Native\Desktop\Facades\Window;

/**
 * Focuses the main window and navigates it to the in-app route an OS
 * notification reference URL carries (D-14).
 *
 * Plan 15-02 fired `NotificationDeepLink` events when the user clicks a
 * native OS notification — the event's `$screenRoute` is an
 * app-emitted route URL (never user input). This listener consumes the
 * event by navigating `Window::current()` to the route. The "focus the
 * window" step is delegated to NativePHP — `Window::current()->url(...)`
 * implicitly brings the focused window forward.
 *
 * Native-chrome carve-out: the listener calls
 * `Native\Desktop\Facades\Window` directly because the contract method
 * the WindowManager binds (`Window::current()->url($url)`) has no
 * container-bound alternative. The file joins the existing facade
 * allow-list in `BoundaryArchTest` + `phpstan.neon`.
 *
 * Trust boundary (T-15-03): `$screenRoute` was generated by
 * `DispatchOsNotification` from the project's own `UrlGenerator` —
 * never built from user input. Destination screens still sit behind
 * `auth` middleware so a click never reaches another user's data.
 *
 * Bundle-only: subscribed only when `nativephp-internal.running=true`.
 * Outside the bundle there is no native shell to focus + navigate.
 */
final class NavigateOnNotificationDeepLink
{
    public function handle(NotificationDeepLink $event): void
    {
        Window::current()->url($event->screenRoute);
    }
}
