#!/usr/bin/env bash
#
# materialize.sh — dereference the mobile shell into a self-contained tree.
#
# The `mobile-app/` root is a thin NativePHP-for-Mobile shell whose shared
# source (app/, Modules/, resources/, routes/, public/, config/*.php, the
# database migration/schema dirs, tests/) lives at the DESKTOP repo root and
# is reached through git-tracked symlinks pointing up to `../` and `../../`.
# Those links are the single-source-of-truth seam for day-to-day development.
#
# Bifrost (the NativePHP cloud build) pulls only the specified directory and
# its children into the build container, so those parent-pointing symlinks
# dangle and the build fails. This script produces a COPY of `mobile-app/`
# with every symlink replaced by the real file/directory it targets — a tree
# that is complete in its own right and can be built from its own root.
#
# The output is intended to be pushed to the dedicated, fully-generated build
# repo that Bifrost is pointed at. It is derived, never hand-edited.
#
# Usage (run from anywhere; paths are resolved against the repo root):
#     mobile-app/scripts/materialize.sh <output-dir>
#
# The output dir is created if absent and is otherwise emptied of tracked
# content by rsync's --delete, so re-running is idempotent.

set -euo pipefail

# --- Resolve the repo root (parent of mobile-app/) regardless of CWD. --------
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
SRC="${REPO_ROOT}/mobile-app"

OUT="${1:?usage: materialize.sh <output-dir>}"
mkdir -p "${OUT}"
OUT="$(cd "${OUT}" && pwd)"

if [[ "${OUT}" == "${SRC}"* ]]; then
    echo "::error:: output dir must be outside mobile-app/ (got ${OUT})" >&2
    exit 2
fi

echo "materialize: ${SRC} -> ${OUT}"

# --- Copy, dereferencing every symlink into real content. --------------------
# --copy-links (-L) turns each symlink into the file/dir tree it points at, so
# the parent-pointing links become real content local to the output tree.
#
# Excludes, and why each is safe to drop:
#   vendor/            Bifrost runs `composer install` in-container.
#   node_modules/      restored by the frontend build, never shipped as-is.
#   .env*              secrets are injected by Bifrost/CI, never committed.
#   storage runtime    caches/logs/sessions are per-run, regenerated on device.
#   bootstrap/cache    dev-tree provider caches fatal a --no-dev bundle.
#   native scaffolds   ios/, android/, nativephp/, build/ are regenerated by
#                      `native:install` in the build container.
#   .phpunit.cache     machine-local test result cache.
#   .git               the build repo carries its own history.
rsync -a --copy-links --delete \
    --exclude='/vendor/' \
    --exclude='/node_modules/' \
    --exclude='.env' \
    --exclude='.env.*' \
    --exclude='/storage/framework/cache/*' \
    --exclude='/storage/framework/sessions/*' \
    --exclude='/storage/framework/testing/*' \
    --exclude='/storage/framework/views/*' \
    --exclude='/storage/logs/*' \
    --exclude='/storage/app/private/' \
    --exclude='/storage/app/public/' \
    --exclude='/storage/app/secrets/' \
    --exclude='/bootstrap/cache/*.php' \
    --exclude='/ios/' \
    --exclude='/android/' \
    --exclude='/nativephp/' \
    --exclude='/build/' \
    --exclude='.phpunit.cache' \
    --exclude='.DS_Store' \
    --exclude='.git/' \
    "${SRC}/" "${OUT}/"

# --- Ensure Laravel's writable runtime directories exist. --------------------
# These dirs hold only machine-generated, gitignored content, so git never
# tracks the empty dirs and they vanish from a clean checkout — which is what
# the build repo is. Their ABSENCE is fatal: `composer install` runs
# `artisan package:discover`, which aborts with "bootstrap/cache directory must
# be present and writable"; rendering that error under --ansi then resolves the
# unbound `request` binding and surfaces the misleading "Target class [request]
# does not exist" instead. A tracked `.gitkeep` keeps each dir present (and
# writable) in the build container.
for d in \
    bootstrap/cache \
    storage/framework/cache/data \
    storage/framework/sessions \
    storage/framework/views \
    storage/framework/testing \
    storage/logs \
    storage/app/public
do
    mkdir -p "${OUT}/${d}"
    : > "${OUT}/${d}/.gitkeep"
done

# --- Guard: the output must be self-contained. -------------------------------
# Any symlink surviving here, or any that escaped to an absolute/parent path,
# means the copy is not buildable in isolation — fail loudly rather than let
# Bifrost hit it.
if leftover="$(find "${OUT}" -type l -print -quit 2>/dev/null)" && [[ -n "${leftover}" ]]; then
    echo "::error:: symlink survived materialization: ${leftover}" >&2
    exit 3
fi

echo "materialize: OK — self-contained tree at ${OUT}"
