#!/usr/bin/env php
<?php

declare(strict_types=1);

/**
 * Injects a persistent macOS menu-bar tray icon into the bundled NativePHP
 * Electron main process.
 *
 * Runs as a `prebuild` hook (see config/nativephp.php). It patches the
 * project-local `nativephp/electron/src/main/index.js` to:
 *
 *   1. Import `Menu`, `Tray`, `nativeImage` from electron alongside the
 *      existing `app` import.
 *   2. Bind a module-scoped `tray` variable so the GC keeps it alive for
 *      the whole app lifetime.
 *   3. On `app.whenReady()`, poll until NativePHP has finished bootstrap
 *      (i.e. `state.electronApiPort` is set), then construct a native
 *      Electron `Tray` with the bundled `tray-icon.png` flagged as a
 *      template image so macOS auto-tints it for the active menu bar
 *      appearance. The Tray has a three-row context menu (Open Beatrax /
 *      Scan email now / Quit) whose handlers either:
 *        - show + focus the existing main BrowserWindow if it lives in
 *          `state.windows.main`, OR
 *        - if the main window has been closed via the X button (its
 *          entry has been deleted from `state.windows`), POST to the
 *          NativePHP Electron API `/api/window/open` endpoint with the
 *          same payload `WindowManager::open('main')` would have sent,
 *          which constructs a fresh BrowserWindow.
 *
 * Why this is needed:
 *
 *   NativePHP's `MenuBar` facade is a wrapper around the npm `menubar`
 *   library which builds a popover-style menubar app. Even with
 *   `onlyShowContextMenu(true)` the right-click menu items go through
 *   `compileMenu` in the dist's helper module — that compiles `link`-type
 *   items into a click handler that early-returns when `focusedWindow` is
 *   null. So once the main window is closed (the close handler in
 *   window.js deletes `state.windows[id]`), the tray's "Open Beatrax"
 *   item silently does nothing. That is the wrong paradigm for a
 *   persistent menu-bar icon that re-opens the main window after the X
 *   button was used.
 *
 *   The proper paradigm is a native Electron `Tray` instance owned by the
 *   main process — lives for the app lifetime regardless of any
 *   BrowserWindow's state, and its click handlers can show / focus / re-
 *   create the main BrowserWindow directly. This script wires exactly
 *   that.
 *
 *   The asset itself (`resources/brand/tray-icon.png` 22x22 + the @2x
 *   sibling) is committed as a black-on-transparent silhouette. The
 *   Electron Tray here flags both as a template image via
 *   `nativeImage.setTemplateImage(true)` so macOS recolors it to match
 *   the menu-bar appearance (white in dark, black in light).
 *
 *   `nativephp/` is gitignored (regenerated by `native:install --publish`),
 *   so the patch must be re-applied every build.
 *
 * The hook is idempotent: an index.js that already contains the inject
 * marker is left untouched.
 *
 * Exit codes:
 *   0  patched, or already correct
 *   1  the electron main process source could not be located or patched
 */
/**
 * Marker comment line written into the patched file. The presence of this
 * marker is the idempotency check.
 */
const TRAY_PATCH_MARKER = '// ── Beatrax persistent menu-bar tray ──';

$isDirectlyInvoked = PHP_SAPI === 'cli'
    && isset($_SERVER['argv'][0])
    && realpath((string) $_SERVER['argv'][0]) === __FILE__;

if ($isDirectlyInvoked) {
    $projectRoot = dirname(__DIR__);
    $indexJsPath = $projectRoot.'/nativephp/electron/src/main/index.js';

    if (! is_file($indexJsPath)) {
        fwrite(STDERR, "nativephp_inject_persistent_tray: {$indexJsPath} not found — run `php artisan native:install --publish` first.\n");

        exit(1);
    }

    $source = file_get_contents($indexJsPath);

    if ($source === false) {
        fwrite(STDERR, "nativephp_inject_persistent_tray: could not read {$indexJsPath}\n");

        exit(1);
    }

    [$patched, $reason] = injectPersistentTray($source);

    if ($patched === null) {
        fwrite(STDERR, "nativephp_inject_persistent_tray: {$reason}\n");

        exit(1);
    }

    if ($patched === $source) {
        fwrite(STDOUT, "nativephp_inject_persistent_tray: index.js already wired — skipping.\n");

        exit(0);
    }

    if (file_put_contents($indexJsPath, $patched) === false) {
        fwrite(STDERR, "nativephp_inject_persistent_tray: could not write {$indexJsPath}\n");

        exit(1);
    }

    fwrite(STDOUT, "nativephp_inject_persistent_tray: wired persistent Electron Tray into {$indexJsPath}.\n");

    exit(0);
}

/**
 * Performs the patch on an in-memory source string.
 *
 *  1. Replace the electron import line `import { app } from 'electron';`
 *     with one that also pulls Menu, Tray and nativeImage.
 *  2. Inject the tray-setup block immediately after the `NativePHP.bootstrap(...)`
 *     call site. That position is chosen because:
 *        - It sits inside the `else { ... }` branch of the single-instance
 *          guard — so we don't create a tray in the duplicate-launch process
 *          that is about to exit.
 *        - It is after `NativePHP.bootstrap()` registers the
 *          `app.whenReady()` lifecycle, so adding our own `app.whenReady()`
 *          listener composes cleanly (Electron supports multiple listeners
 *          and queues them in registration order).
 *
 * @return array{0: string|null, 1: string} [patched source or null on failure, human-readable status]
 */
function injectPersistentTray(string $source): array
{
    // Drift-resistant idempotency: the marker text carries the brand name
    // and was rebranded in 16-02 (diederik→Beatrax), so an older patch
    // run could have written the previous marker into the on-disk
    // (gitignored) index.js. The injected `installPersistentTray()`
    // function name is hard-coded in `traySetupBlock()` below, so its
    // presence is a stable signal that the patch is already applied
    // regardless of brand drift.
    if (str_contains($source, TRAY_PATCH_MARKER)
        || str_contains($source, 'function installPersistentTray()')) {
        return [$source, 'already-patched'];
    }

    // 1. Broaden the electron named imports. NativePHP's published main
    //    process imports only `app`; we also need Menu, Tray, and
    //    nativeImage.
    $oldImport = "import { app } from 'electron';";
    $newImport = "import { app, Menu, Tray, nativeImage } from 'electron';";

    if (! str_contains($source, $oldImport)) {
        return [null, 'could not locate the `import { app } from \'electron\';` line to broaden'];
    }

    $source = str_replace($oldImport, $newImport, $source);

    // 2. Find the `NativePHP.bootstrap(...)` call so we can splice the
    //    tray-setup block in directly after it. The exact source line
    //    NativePHP publishes is:
    //
    //      NativePHP.bootstrap(app, defaultIcon, phpBinary, certificate, appPath);
    //
    //    We balance parens defensively in case a future NativePHP release
    //    reshapes the argument list across multiple lines.
    $needle = 'NativePHP.bootstrap(';
    $start = strpos($source, $needle);

    if ($start === false) {
        return [null, 'could not locate the `NativePHP.bootstrap(...)` call site'];
    }

    $afterCallEnd = findExpressionEnd($source, $start + strlen($needle));

    if ($afterCallEnd === null) {
        return [null, 'failed to balance parens around NativePHP.bootstrap(...) — source malformed?'];
    }

    // Walk past an optional trailing `;` so we splice on a clean statement
    // boundary.
    if (isset($source[$afterCallEnd]) && $source[$afterCallEnd] === ';') {
        $afterCallEnd++;
    }

    $injection = "\n\n".traySetupBlock()."\n";

    $patched = substr($source, 0, $afterCallEnd).$injection.substr($source, $afterCallEnd);

    return [$patched, 'patched'];
}

/**
 * Walks $source from $start (which sits at the character immediately after
 * the opening `(` of a JS call) and returns the index of the character
 * immediately after the matching `)`. Returns null on imbalance.
 *
 * Handles string literals (single, double, template) and escape sequences
 * so a `)` inside a string does not close the call.
 */
function findExpressionEnd(string $source, int $start): ?int
{
    $depth = 1;
    $i = $start;
    $len = strlen($source);
    $inString = null;

    while ($i < $len) {
        $ch = $source[$i];

        if ($inString !== null) {
            if ($ch === '\\') {
                $i += 2;

                continue;
            }
            if ($ch === $inString) {
                $inString = null;
            }
            $i++;

            continue;
        }

        if ($ch === "'" || $ch === '"' || $ch === '`') {
            $inString = $ch;
            $i++;

            continue;
        }

        if ($ch === '(') {
            $depth++;
        } elseif ($ch === ')') {
            $depth--;
            if ($depth === 0) {
                return $i + 1;
            }
        }

        $i++;
    }

    return null;
}

/**
 * The literal JavaScript block injected after `NativePHP.bootstrap(...)`.
 *
 * The block:
 *
 *   - Constructs a single Electron `Tray` retained in a module-scoped
 *     variable so V8 cannot reclaim it.
 *
 *   - Loads the icon as a NativeImage from the staged
 *     `<buildPath>/tray-icon.png` (the staging step puts this file in
 *     `nativephp/electron/build/` alongside `icon.png`). The image is
 *     flagged as a template image so macOS auto-tints it; the 2x sibling
 *     (`tray-icon@2x.png`) is loaded by Electron automatically when present.
 *
 *   - Builds the verbatim three-row context menu (UI-SPEC labels:
 *     "Open Beatrax", "Scan email now", "Quit"). The first two items show
 *     or re-open the main window and (for "Scan email now") navigate it to
 *     the inboxes page. "Quit" calls `app.quit()`.
 *
 *   - Wires a tray click handler that mirrors "Open Beatrax" so a single
 *     left-click on the icon also brings the main window back.
 *
 *   - The show-or-recreate helper inspects `state.windows.main`:
 *       * present  → `.show()` then `.focus()` (and `.restore()` if
 *                    minimized).
 *       * missing  → POST to the Electron API `/api/window/open` with the
 *                    same payload `WindowManager::open('main')` produces.
 *                    The endpoint either re-shows an existing window with
 *                    the same id (idempotent), or constructs a fresh
 *                    BrowserWindow with the persisted window-state-keeper
 *                    geometry. The dimensions / id / url / rememberState
 *                    flag here MUST stay in sync with
 *                    `NativeAppServiceProvider::boot()`'s window
 *                    configuration, otherwise the re-opened window will
 *                    have different geometry than the originally-opened
 *                    one (which is jarring for the user).
 */
function traySetupBlock(): string
{
    $marker = TRAY_PATCH_MARKER;

    return <<<JS
        {$marker}
        // Owned, persistent macOS menu-bar tray. Lives for the entire app
        // lifetime (V8 keeps the reference reachable through the module-
        // scoped `tray` binding). Replaces NativePHP's MenuBar facade, which
        // wraps the popover-style npm `menubar` library and couples the
        // tray menu items to the focused BrowserWindow — the wrong paradigm
        // for D-09 (the tray must outlive the main window so it can
        // re-open it after the user closes via the X button).
        let tray = null;

        // Base window-open payload posted to the NativePHP Electron API
        // `/api/window/open` route when the main window has been closed via
        // the X button (its entry has been deleted from `state.windows`).
        // The shape MUST stay aligned with what `WindowManager::open('main')
        // ->width(1100)->height(800)->rememberState()` produces on the PHP
        // side — every key the route handler reads is listed so a future
        // upstream change that adds a required key surfaces as an obvious
        // window-construction regression. `url` is filled at click time
        // because it depends on the dynamically-assigned NativePHP php
        // server port.
        const TRAY_MAIN_WINDOW_PAYLOAD = {
            id: 'main',
            url: null,
            width: 1100,
            height: 800,
            rememberState: true,
            showDevTools: false,
            resizable: true,
            movable: true,
            minimizable: true,
            maximizable: true,
            closable: true,
            focusable: true,
            hasShadow: true,
            frame: true,
            title: 'Beatrax',
            titleBarStyle: 'default',
            windowButtonVisibility: true,
            alwaysOnTop: false,
            fullscreen: false,
            fullscreenable: true,
            kiosk: false,
            autoHideMenuBar: false,
            zoomFactor: 1.0,
            preventLeaveDomain: false,
            preventLeavePage: false,
            suppressNewWindows: false,
            webPreferences: {},
        };

        async function bringMainWindowToFront({ inboxes = false } = {}) {
            try {
                const NativePHPState = (await import('#plugin/server/state.js')).default;
                const existing = NativePHPState.windows && NativePHPState.windows.main;
                if (existing) {
                    if (existing.isMinimized()) existing.restore();
                    if (!existing.isVisible()) existing.show();
                    existing.focus();
                    if (inboxes) {
                        const phpPort = NativePHPState.phpPort;
                        if (phpPort) {
                            existing.loadURL(`http://127.0.0.1:\${phpPort}/inboxes?_windowId=main`);
                        }
                    }
                    return;
                }
                // Main window was closed via the X button. POST to the
                // Electron API to reconstruct it with the same parameters
                // the Laravel WindowManager would have sent.
                const port = NativePHPState.electronApiPort;
                const secret = NativePHPState.randomSecret;
                const phpPort = NativePHPState.phpPort;
                if (!port || !secret || !phpPort) {
                    return; // bootstrap not finished yet; tray clicked too early
                }
                const targetUrl = inboxes
                    ? `http://127.0.0.1:\${phpPort}/inboxes`
                    : `http://127.0.0.1:\${phpPort}/`;
                const payload = { ...TRAY_MAIN_WINDOW_PAYLOAD, url: targetUrl };
                await axios.post(
                    `http://127.0.0.1:\${port}/api/window/open`,
                    payload,
                    { headers: { 'x-nativephp-secret': secret } },
                );
            } catch {
                // best-effort — same rationale as the existing
                // forwardFileOpenToLaravel helper above
            }
        }

        function installPersistentTray() {
            if (tray) {
                return;
            }
            const trayIconPath = path.join(buildPath, 'tray-icon.png');
            const image = nativeImage.createFromPath(trayIconPath);
            image.setTemplateImage(true);
            tray = new Tray(image);
            tray.setToolTip('Beatrax');
            const contextMenu = Menu.buildFromTemplate([
                {
                    label: 'Open Beatrax',
                    click: () => { bringMainWindowToFront(); },
                },
                {
                    label: 'Scan email now',
                    click: () => { bringMainWindowToFront({ inboxes: true }); },
                },
                { type: 'separator' },
                {
                    label: 'Quit',
                    click: () => { app.quit(); },
                },
            ]);
            tray.setContextMenu(contextMenu);
            tray.on('click', () => { bringMainWindowToFront(); });
        }

        app.whenReady().then(async () => {
            // Wait for NativePHP's own bootstrap to publish the electron
            // API port + the random secret. Without these, the show-or-
            // recreate POST is unauthenticated and fails.
            const NativePHPState = (await import('#plugin/server/state.js')).default;
            const deadline = Date.now() + 30_000;
            while (Date.now() < deadline) {
                if (NativePHPState.electronApiPort && NativePHPState.randomSecret) {
                    installPersistentTray();
                    return;
                }
                await new Promise((r) => setTimeout(r, 250));
            }
        });
        JS;
}
