<?php

declare(strict_types=1);

require_once __DIR__.'/nativephp_scaffold_root.php';

/*
 * Give the iOS runtime an upload ceiling it can actually restore a backup with.
 *
 * The generated shell writes the whole iOS php.ini itself, and it writes two
 * lines: `curl.cainfo` and `openssl.cafile`. Every other directive is the
 * bundled interpreter's stock value, which means `post_max_size = 8M`.
 *
 * That is not 8 MB of file. Uploads on iOS do not arrive as multipart --
 * WebKit hands a custom-scheme handler only string bodies, so the client
 * base64-encodes the file into a JSON body instead (`resources/js/mobile-upload.js`,
 * `EncodedUploadTransport`). base64 costs four bytes for every three, so the
 * stock 8,388,608-byte body ceiling is a 6,291,456-byte FILE ceiling.
 *
 * Measured on an iPhone 12 mini before this patch, restoring an encrypted
 * backup: 6,000,000 bytes uploaded, 6,500,000 bytes did not, and the app's own
 * 8,046,695-byte backup -- a 3,306-transaction ledger, which is small -- was
 * dropped every time. `upload_max_filesize` never enters into it: the transport
 * reconstructs the UploadedFile itself, so no SAPI upload happens for that
 * directive to bind on. It is set anyway for parity with the desktop shell and
 * to be correct if a multipart path ever exists.
 *
 * The desktop shell already solved this in `NativeAppServiceProvider::phpIni()`
 * (20M/20M), with a comment describing exactly this failure. Mobile never got
 * the same treatment, so the app could produce a backup it could not read back.
 *
 * POST_MAX_SIZE is not 20M to match: it must clear UPLOAD_MAX_FILESIZE times
 * 4/3 for the encoding, plus the JSON envelope, or the file limit is decorative.
 * 32M carries a 20M file with room for the envelope.
 *
 * This block is the whole php.ini the iOS shell writes, so the one other
 * directive the stock interpreter gets wrong ships with it rather than through
 * a second patch fighting the same anchor. `zend.exception_ignore_args` is Off
 * by default, and then anything rendering a stack trace writes the first 15
 * characters of every string argument into the daily log -- on a parse frame,
 * a row of the reader's bank statement. `SafeTrace` assembles its own frames
 * and depends on none of this; the directive covers the traces nothing in this
 * repository formats.
 *
 * The generated tree is regenerated by `native:install`, so this is applied
 * from composer's hooks rather than hand-edited. It is idempotent, and a
 * missing anchor is a hard failure rather than a silent skip: an unpatched
 * shell degrades to exactly the behaviour this exists to fix, and does it
 * without a line in any log.
 */

const BEATRAX_IOS_UPLOAD_MAX_FILESIZE = '20M';

const BEATRAX_IOS_POST_MAX_SIZE = '32M';

const BEATRAX_IOS_EXCEPTION_IGNORE_ARGS = '1';

// Both writers hold a byte-identical heredoc. NativePHPApp builds `caPath`
// locally and PersistentPHPRuntime takes it as a parameter, which does not
// change the lines being matched.
$targets = [
    'ios/NativePHP/NativePHPApp.swift',
    'ios/NativePHP/Bridge/PersistentPHPRuntime.swift',
];

$anchor = <<<'SWIFT'
        let phpIni = """
        curl.cainfo="\(caPath)"
        openssl.cafile="\(caPath)"
        """
SWIFT;

$replacement = sprintf(
    <<<'SWIFT'
        // Patched by scripts/nativephp_ios_upload_limits.php -- the stock
        // post_max_size of 8M is a 6.29 MB file ceiling once the base64
        // upload transport has inflated the body, and stock
        // zend.exception_ignore_args puts statement rows in the log.
        let phpIni = """
        curl.cainfo="\(caPath)"
        openssl.cafile="\(caPath)"
        upload_max_filesize=%s
        post_max_size=%s
        zend.exception_ignore_args=%s
        """
SWIFT,
    BEATRAX_IOS_UPLOAD_MAX_FILESIZE,
    BEATRAX_IOS_POST_MAX_SIZE,
    BEATRAX_IOS_EXCEPTION_IGNORE_ARGS,
);

$patchedAny = false;

foreach ($targets as $relative) {
    $target = beatraxScaffoldPath($relative) ?? '';

    if (! is_file($target)) {
        fwrite(STDOUT, "nativephp_ios_upload_limits: no iOS scaffold yet ({$relative}) — skipping.\n");

        continue;
    }

    $source = (string) file_get_contents($target);

    if (str_contains($source, 'post_max_size')) {
        fwrite(STDOUT, "nativephp_ios_upload_limits: already patched ({$relative}).\n");

        continue;
    }

    if (! str_contains($source, $anchor)) {
        fwrite(STDERR, "nativephp_ios_upload_limits: php.ini anchor not found in {$target}.\n");
        fwrite(STDERR, "The generated shell changed how it writes php.ini; re-check the upload ceiling before shipping a build.\n");
        exit(1);
    }

    if (file_put_contents($target, str_replace($anchor, $replacement, $source)) === false) {
        fwrite(STDERR, "nativephp_ios_upload_limits: could not write {$target}.\n");
        exit(1);
    }

    $patchedAny = true;
    fwrite(STDOUT, "nativephp_ios_upload_limits: patched {$relative}.\n");
}

if ($patchedAny) {
    fwrite(STDOUT, 'nativephp_ios_upload_limits: upload_max_filesize='.BEATRAX_IOS_UPLOAD_MAX_FILESIZE.', post_max_size='.BEATRAX_IOS_POST_MAX_SIZE."\n");
}

exit(0);
