#!/usr/bin/env php
<?php

declare(strict_types=1);

/**
 * Forces deterministic ad-hoc macOS code signing for the NativePHP /
 * electron-builder desktop build.
 *
 * Runs as a `prebuild` hook (see config/nativephp.php). It patches the
 * generated `nativephp/electron/electron-builder.mjs` so the `mac`
 * config block contains `identity: null`.
 *
 * Why this is needed:
 *
 *   electron-builder's macOS signing step, when no `mac.identity` is
 *   set, auto-discovers a code-signing identity from the macOS
 *   keychain. If any identity is present (an Xcode-provisioned "Apple
 *   Development" certificate, an expired Developer ID, etc.) the bundle
 *   is partially signed: the app shell stays ad-hoc with an empty Team
 *   ID while the nested "Electron Framework.framework" keeps a
 *   non-empty Team ID. On Apple Silicon dyld aborts at launch because
 *   images mapped into one process have mismatched Team IDs
 *   ("Library not loaded ... different Team IDs").
 *
 *   Setting `identity: null` makes electron-builder always perform a
 *   consistent `--deep` ad-hoc signing pass regardless of keychain
 *   contents, producing a reproducible bundle that launches cleanly.
 *   This requires no paid Apple Developer ID — appropriate for a
 *   local-only build.
 *
 * The NativePHP electron working directory is an install-time artifact
 * regenerated by `native:install`, so this patch is reapplied before
 * every build. It is idempotent: a build whose config already declares
 * `identity` is left untouched.
 *
 * Exit codes:
 *   0  patched, already correct, or nothing to do
 *   1  the electron-builder config could not be patched
 */
$projectRoot = dirname(__DIR__);
$configPath = $projectRoot.'/nativephp/electron/electron-builder.mjs';

if (! is_file($configPath)) {
    // The electron working directory only exists after `native:install`.
    // Nothing to patch yet — let the build proceed and fail loudly itself
    // if the directory is genuinely required.
    fwrite(STDOUT, "nativephp_force_adhoc_signing: no electron-builder.mjs found, skipping.\n");

    exit(0);
}

$source = file_get_contents($configPath);

if ($source === false) {
    fwrite(STDERR, "nativephp_force_adhoc_signing: could not read {$configPath}\n");

    exit(1);
}

if (preg_match('/\bidentity\s*:/', $source) === 1) {
    fwrite(STDOUT, "nativephp_force_adhoc_signing: identity already configured, leaving as-is.\n");

    exit(0);
}

// Insert `identity: null` as the first key of the `mac: { ... }` block.
$patched = preg_replace(
    '/(\bmac:\s*\{)/',
    "$1\n        identity: null, // forced ad-hoc signing — see scripts/nativephp_force_adhoc_signing.php",
    $source,
    1,
    $count
);

if ($patched === null || $count !== 1) {
    fwrite(STDERR, "nativephp_force_adhoc_signing: could not locate a `mac: {` block in {$configPath}\n");

    exit(1);
}

if (file_put_contents($configPath, $patched) === false) {
    fwrite(STDERR, "nativephp_force_adhoc_signing: could not write {$configPath}\n");

    exit(1);
}

fwrite(STDOUT, "nativephp_force_adhoc_signing: injected `identity: null` for deterministic ad-hoc signing.\n");

exit(0);
