#!/usr/bin/env php
<?php

declare(strict_types=1);

/**
 * Marks the macOS system-tray icon as a template image so macOS auto-tints it
 * to the active menu-bar appearance (white in dark menu bar, black in light).
 *
 * Runs as a `prebuild` hook (see config/nativephp.php). It patches the built
 * `nativephp/electron/electron-plugin/dist/server/api/menuBar.js` `/create`
 * route handler so the constructed `Tray` instance has `setTemplateImage(true)`
 * called on its underlying `nativeImage`.
 *
 * Why this is needed:
 *
 *   NativePHP's PHP-side `MenuBar` fluent API has no template-image flag — its
 *   `toArray()` payload never carries one to Electron — and the Electron-side
 *   `/create` handler instantiates `new Tray(icon)` with a raw filesystem path,
 *   never calling `setTemplateImage(true)`. Electron does NOT auto-detect a
 *   template image from a file path passed through `nativeImage.createFromPath`;
 *   the filename-suffix auto-detection only applies to images loaded from the
 *   macOS app bundle Resources via `nativeImage.createFromNamedImage` and
 *   matching `*Template@*x.png` naming on bundle-included assets. Our tray
 *   icon is shipped at `resources/brand/tray-icon.png`, so the flag must be
 *   set explicitly or the icon renders full-color and never adapts to light /
 *   dark menu-bar appearance.
 *
 *   `nativephp/` is gitignored (regenerated by `native:install --publish`),
 *   so the patch must be re-applied every build.
 *
 * The hook is idempotent: a dist file that already calls `setTemplateImage`
 * is left untouched.
 *
 * Exit codes:
 *   0  patched, or already correct
 *   1  the electron-plugin dist file could not be located or patched
 */
// Only execute the patch step when the script is invoked directly from the
// CLI. Including the file from a test (`require_once`) re-uses the helper
// function below without triggering the I/O / exit() side effects, so the
// test runner does not need a populated `nativephp/electron/...` tree.
$isDirectlyInvoked = PHP_SAPI === 'cli'
    && isset($_SERVER['argv'][0])
    && realpath((string) $_SERVER['argv'][0]) === __FILE__;

if ($isDirectlyInvoked) {
    $projectRoot = dirname(__DIR__);

    $distPath = $projectRoot.'/nativephp/electron/electron-plugin/dist/server/api/menuBar.js';

    if (! is_file($distPath)) {
        fwrite(STDERR, "nativephp_patch_tray_template_image: {$distPath} not found — run `php artisan native:install --publish` first.\n");

        exit(1);
    }

    $source = file_get_contents($distPath);

    if ($source === false) {
        fwrite(STDERR, "nativephp_patch_tray_template_image: could not read {$distPath}\n");

        exit(1);
    }

    // Idempotency guard. A previous prebuild run already inserted the
    // template flag — leave the dist alone. The marker is the verbatim
    // call we inject; matching on `setTemplateImage` is sufficient because
    // the upstream file never calls it anywhere else.
    if (str_contains($source, 'setTemplateImage')) {
        fwrite(STDOUT, "nativephp_patch_tray_template_image: dist already calls setTemplateImage — skipping.\n");

        exit(0);
    }

    // Replace `new Tray(<arg>)` with a small IIFE that constructs a
    // NativeImage from the same path argument, flags it as a macOS
    // template image, then passes it to `new Tray`. Electron's Tray
    // accepts either a path string or a pre-built NativeImage; using the
    // NativeImage form lets us call `setTemplateImage(true)` before the
    // Tray is constructed, which is the upstream-recommended path for
    // macOS menu-bar adaptive tinting.
    //
    // The argument to `new Tray(...)` is itself a JS expression that
    // contains nested parentheses (`state.icon.replace('icon.png',
    // 'IconTemplate.png')`), so the matcher has to balance parens rather
    // than rely on a flat `[^)]+` capture — that would truncate at the
    // first inner `)` and corrupt the file.
    [$patched, $count] = replaceFirstNewTrayCall($source);

    if ($patched === null || $count !== 1) {
        fwrite(STDERR, "nativephp_patch_tray_template_image: could not locate the `new Tray(...)` construction in {$distPath}\n");

        exit(1);
    }

    if (file_put_contents($distPath, $patched) === false) {
        fwrite(STDERR, "nativephp_patch_tray_template_image: could not write {$distPath}\n");

        exit(1);
    }

    fwrite(STDOUT, "nativephp_patch_tray_template_image: marked tray icon as macOS template image.\n");

    exit(0);
}

/**
 * Replaces the first `new Tray(<expr>)` call in $source with an IIFE that
 * constructs a NativeImage from the same path argument, flags it as a macOS
 * template image, then hands the image to `new Tray`.
 *
 * The matcher walks $source character-by-character to balance parentheses
 * and skip string contents — a flat regex like `new Tray\(([^)]+)\)` would
 * truncate at the first inner `)` (e.g. the closing paren of
 * `state.icon.replace('icon.png', 'IconTemplate.png')`) and produce a broken
 * file.
 *
 * @return array{0: string|null, 1: int} [patched source or null on failure, replacement count]
 */
function replaceFirstNewTrayCall(string $source): array
{
    $needle = 'new Tray(';
    $start = strpos($source, $needle);

    if ($start === false) {
        return [null, 0];
    }

    $argStart = $start + strlen($needle);
    $depth = 1;
    $i = $argStart;
    $len = strlen($source);
    $inString = null; // null | "'" | '"' | '`'

    while ($i < $len) {
        $ch = $source[$i];

        if ($inString !== null) {
            if ($ch === '\\') {
                // Skip escaped character (covers \', \", \\, etc.)
                $i += 2;

                continue;
            }
            if ($ch === $inString) {
                $inString = null;
            }
            $i++;

            continue;
        }

        if ($ch === "'" || $ch === '"' || $ch === '`') {
            $inString = $ch;
            $i++;

            continue;
        }

        if ($ch === '(') {
            $depth++;
        } elseif ($ch === ')') {
            $depth--;
            if ($depth === 0) {
                break;
            }
        }

        $i++;
    }

    if ($depth !== 0) {
        return [null, 0];
    }

    $arg = substr($source, $argStart, $i - $argStart);

    $replacement = "new Tray((() => { const _img = require('electron').nativeImage.createFromPath({$arg}); _img.setTemplateImage(true); return _img; })())";

    $patched = substr($source, 0, $start).$replacement.substr($source, $i + 1);

    return [$patched, 1];
}
