<?php

declare(strict_types=1);

require_once __DIR__.'/nativephp_scaffold_root.php';

/*
 * Give the Android runtime the same upload ceiling iOS already has.
 *
 * `LaravelEnvironment.setupEnvironment()` writes the whole Android php.ini
 * itself, and it writes two lines: `curl.cainfo` and `openssl.cafile`. Every
 * other directive is the bundled interpreter's stock value, which means
 * `post_max_size = 8M` — byte for byte the defect
 * `nativephp_ios_upload_limits.php` was written for, on the platform that
 * never got the fix.
 *
 * Both shells share one transport: `EncodedUploadTransport` and
 * `resources/js/mobile-upload.js` are gated on `isMobileRuntime()`, not on
 * platform, so an Android upload is base64 in a JSON body exactly as an iOS
 * one is. base64 costs four bytes for every three, so the stock 8,388,608-byte
 * body ceiling is a 6,291,456-byte FILE ceiling — while the client-side guard
 * in mobile-upload.js accepts 20 MB. Between those two numbers an import or an
 * encrypted-backup restore is accepted by the phone and dropped by PHP.
 *
 * The values match the iOS script, and POST_MAX_SIZE is deliberately larger
 * than UPLOAD_MAX_FILESIZE: it has to clear the file limit times 4/3 for the
 * encoding plus the JSON envelope, or the file limit is decorative.
 *
 * This block is the whole php.ini the Android shell writes, so the one other
 * directive the stock interpreter gets wrong ships with it rather than through
 * a second patch fighting the same anchor. `zend.exception_ignore_args` is Off
 * by default, and then anything rendering a stack trace writes the first 15
 * characters of every string argument into the daily log — on a parse frame,
 * a row of the reader's bank statement. `SafeTrace` assembles its own frames
 * and depends on none of this; the directive covers the traces nothing in this
 * repository formats.
 *
 * The generated tree is regenerated by `native:install`, so this is applied
 * from composer's hooks rather than hand-edited. It is idempotent, and a
 * missing anchor is a hard failure rather than a silent skip: an unpatched
 * shell degrades to exactly the behaviour this exists to fix, and does it
 * without a line in any log.
 */

const BEATRAX_ANDROID_UPLOAD_MAX_FILESIZE = '20M';

const BEATRAX_ANDROID_POST_MAX_SIZE = '32M';

const BEATRAX_ANDROID_EXCEPTION_IGNORE_ARGS = '1';

$relative = 'android/app/src/main/java/com/nativephp/mobile/bridge/LaravelEnvironment.kt';

$anchor = <<<'KOTLIN'
                val phpIni = """
curl.cainfo="${context.filesDir.absolutePath}/$CACERT_FILE"
openssl.cafile="${context.filesDir.absolutePath}/$CACERT_FILE"
"""
KOTLIN;

$replacement = sprintf(
    <<<'KOTLIN'
                // Patched by scripts/nativephp_android_upload_limits.php -- the
                // stock post_max_size of 8M is a 6.29 MB file ceiling once the
                // base64 upload transport has inflated the body, and stock
                // zend.exception_ignore_args puts statement rows in the log.
                val phpIni = """
curl.cainfo="${context.filesDir.absolutePath}/$CACERT_FILE"
openssl.cafile="${context.filesDir.absolutePath}/$CACERT_FILE"
upload_max_filesize=%s
post_max_size=%s
zend.exception_ignore_args=%s
"""
KOTLIN,
    BEATRAX_ANDROID_UPLOAD_MAX_FILESIZE,
    BEATRAX_ANDROID_POST_MAX_SIZE,
    BEATRAX_ANDROID_EXCEPTION_IGNORE_ARGS,
);

$target = beatraxScaffoldPath($relative) ?? '';

if (! is_file($target)) {
    fwrite(STDOUT, "nativephp_android_upload_limits: no Android scaffold yet — skipping.\n");

    exit(0);
}

$source = (string) file_get_contents($target);

if (str_contains($source, 'post_max_size')) {
    fwrite(STDOUT, "nativephp_android_upload_limits: already patched.\n");

    exit(0);
}

if (! str_contains($source, $anchor)) {
    fwrite(STDERR, "nativephp_android_upload_limits: php.ini anchor not found in {$target}.\n");
    fwrite(STDERR, "The generated shell changed how it writes php.ini; re-check the upload ceiling before shipping a build.\n");
    exit(1);
}

if (file_put_contents($target, str_replace($anchor, $replacement, $source)) === false) {
    fwrite(STDERR, "nativephp_android_upload_limits: could not write {$target}.\n");
    exit(1);
}

fwrite(
    STDOUT,
    'nativephp_android_upload_limits: patched — upload_max_filesize='
    .BEATRAX_ANDROID_UPLOAD_MAX_FILESIZE.', post_max_size='.BEATRAX_ANDROID_POST_MAX_SIZE."\n",
);

exit(0);
