#!/usr/bin/env php
<?php

declare(strict_types=1);

/**
 * Registers `.csv` and `.eml` as document types the OS routes to Beatrax.
 *
 * Why this is needed:
 *
 *   `FileOpenIntake` and its listeners have always been able to accept an
 *   OS-supplied path, and NativePHP's Electron plugin already forwards
 *   macOS `app.on('open-file')` to the PHP `Native\Desktop\Events\App\OpenFile`
 *   event. None of it could ever run, because nothing told the OS that
 *   Beatrax opens those files: electron-builder writes the macOS
 *   `CFBundleDocumentTypes`, the Windows registry entries and the Linux
 *   `.desktop` `MimeType=` line from a `fileAssociations` key, and NativePHP's
 *   published `electron-builder.mjs` declares none. Without the OS binding,
 *   `open-file` never fires and no argv ever carries a document path.
 *
 *   NativePHP 2.2 exposes no config key for this, so the block is injected
 *   into the published builder config as a `prebuild` hook — `nativephp/` is
 *   gitignored and regenerated by `native:install --publish`, so a hand edit
 *   does not survive.
 *
 * The hook is idempotent: a config that already declares fileAssociations is
 * left untouched.
 *
 * Exit codes:
 *   0  patched, or already correct
 *   1  the builder config could not be located or patched
 */
/**
 * The key whose presence is the idempotency check.
 */
const FILE_ASSOCIATION_MARKER = 'fileAssociations:';

/**
 * The top-level key the block is spliced in front of. Chosen because it is
 * electron-builder's other OS-registration key, so the two sit together.
 */
const FILE_ASSOCIATION_ANCHOR = '    protocols: {';

$isDirectlyInvoked = PHP_SAPI === 'cli'
    && isset($_SERVER['argv'][0])
    && realpath((string) $_SERVER['argv'][0]) === __FILE__;

if ($isDirectlyInvoked) {
    $builderPath = dirname(__DIR__).'/nativephp/electron/electron-builder.mjs';

    if (! is_file($builderPath)) {
        fwrite(STDERR, "nativephp_inject_file_associations: {$builderPath} not found — run `php artisan native:install --publish` first.\n");

        exit(1);
    }

    $source = file_get_contents($builderPath);

    if ($source === false) {
        fwrite(STDERR, "nativephp_inject_file_associations: could not read {$builderPath}\n");

        exit(1);
    }

    [$patched, $reason] = injectFileAssociations($source);

    if ($patched === null) {
        fwrite(STDERR, "nativephp_inject_file_associations: {$reason}\n");

        exit(1);
    }

    if ($patched === $source) {
        fwrite(STDOUT, "nativephp_inject_file_associations: already declared — skipping.\n");

        exit(0);
    }

    if (file_put_contents($builderPath, $patched) === false) {
        fwrite(STDERR, "nativephp_inject_file_associations: could not write {$builderPath}\n");

        exit(1);
    }

    fwrite(STDOUT, "nativephp_inject_file_associations: declared .csv/.eml document types in {$builderPath}.\n");

    exit(0);
}

/**
 * @return array{0: string|null, 1: string} [patched source or null on failure, human-readable status]
 */
function injectFileAssociations(string $source): array
{
    if (str_contains($source, FILE_ASSOCIATION_MARKER)) {
        return [$source, 'already-patched'];
    }

    $at = strpos($source, FILE_ASSOCIATION_ANCHOR);

    if ($at === false) {
        return [null, 'could not locate the `protocols: {` key to anchor fileAssociations against'];
    }

    $block = fileAssociationsBlock()."\n";

    return [substr($source, 0, $at).$block.substr($source, $at), 'patched'];
}

/**
 * The extensions declared to the OS. This list and
 * `FileOpenIntake::SUPPORTED_EXTENSIONS` are two halves of one decision —
 * an extension the OS routes here that the intake refuses is a double-click
 * that opens the app and does nothing.
 *
 * @return array<string, array{name: string, description: string, role: string, mimeType: string}>
 */
function fileAssociationTypes(): array
{
    return [
        'csv' => [
            'name' => 'Comma-Separated Values',
            'description' => 'Bank or PayPal CSV export',
            // macOS CFBundleTypeRole. Editor because an import writes derived
            // data back; Windows ignores it, Linux reads mimeType instead.
            'role' => 'Editor',
            'mimeType' => 'text/csv',
        ],
        'eml' => [
            'name' => 'Email Message',
            'description' => 'Email receipt for import',
            'role' => 'Viewer',
            'mimeType' => 'message/rfc822',
        ],
    ];
}

function fileAssociationsBlock(): string
{
    $lines = ['    fileAssociations: ['];

    foreach (fileAssociationTypes() as $ext => $type) {
        $lines[] = '        {';
        $lines[] = "            ext: '{$ext}',";
        $lines[] = "            name: '{$type['name']}',";
        $lines[] = "            description: '{$type['description']}',";
        $lines[] = "            role: '{$type['role']}',";
        $lines[] = "            mimeType: '{$type['mimeType']}',";
        $lines[] = '        },';
    }

    $lines[] = '    ],';

    return implode("\n", $lines);
}
