<?php

declare(strict_types=1);

/*
 * Save a downloaded file on iOS instead of navigating onto it.
 *
 * The generated navigation policy special-cases http/https/tel/mailto/sms/
 * facetime and falls through to `decisionHandler(.allow)` for everything else,
 * and no WKDownloadDelegate exists anywhere in the shell. A page that builds a
 * blob: URL and clicks an `<a download>` — the ordinary way a web app hands
 * over a file — therefore navigates the WebView *onto the blob*. The app is
 * replaced by its own raw bytes on a bare white page with no chrome, no back
 * gesture (allowsBackForwardNavigationGestures is false), and no file saved.
 * Killing the app is the only way out.
 *
 * Measured on the device: "Downloaden als .txt" on the recovery-codes screen
 * left `location.href` at `blob:php://127.0.0.1/79091edc-…` showing the ten
 * codes as plain text, and the tax page's CSV export did the same. The
 * recovery-codes instance destroys one-time data: those codes are shown once,
 * they are the only way back into a locked-out account, and the screen that
 * displays them is gone the moment Save is tapped.
 *
 * `.download` rather than `.cancel`: cancelling would trade "strands the user"
 * for "the button does nothing", which is not a fix. The file is written to a
 * temporary directory and then offered through the share sheet, because that
 * is how a file leaves an app on iOS — "Save to Files" inside it is what a
 * person means when they tap Download.
 *
 * The generated tree is regenerated by `native:install`, so this is applied
 * from composer's hooks rather than hand-edited. It is idempotent, and a
 * missing anchor is a hard failure rather than a silent skip, because an
 * unpatched shell degrades to exactly the behaviour this exists to fix.
 */

$target = __DIR__.'/../mobile-app/nativephp/ios/NativePHP/ContentView.swift';

if (! is_file($target)) {
    // The native scaffold is generated on demand and is absent from a fresh
    // checkout; there is nothing to patch until `native:install` has run.
    fwrite(STDOUT, "nativephp_ios_download_delegate: no iOS scaffold yet — skipping.\n");
    exit(0);
}

$source = (string) file_get_contents($target);

if (str_contains($source, 'WKDownloadDelegate')) {
    fwrite(STDOUT, "nativephp_ios_download_delegate: already patched.\n");
    exit(0);
}

$declarationAnchor = "    class Coordinator: NSObject, WKNavigationDelegate {\n";

if (! str_contains($source, $declarationAnchor)) {
    fwrite(STDERR, "nativephp_ios_download_delegate: Coordinator anchor not found in {$target}.\n");
    fwrite(STDERR, "The generated shell changed shape; re-check the navigation delegate before shipping a build.\n");
    exit(1);
}

$patched = str_replace(
    $declarationAnchor,
    "    class Coordinator: NSObject, WKNavigationDelegate, WKDownloadDelegate {\n",
    $source,
);

$policyAnchor = "            // Open external URLs and system schemes with the system handler\n";

if (! str_contains($patched, $policyAnchor)) {
    fwrite(STDERR, "nativephp_ios_download_delegate: navigation-policy anchor not found in {$target}.\n");
    fwrite(STDERR, "The generated shell changed shape; a blob: navigation would still strand the WebView.\n");
    exit(1);
}

$policyBranch = <<<'SWIFT'
            // Added by scripts/nativephp_ios_download_delegate.php — a page
            // that creates a blob: URL and clicks an <a download> is asking to
            // save a file, not to navigate. Letting it navigate replaces the
            // app with its own raw bytes and saves nothing.
            if navigationAction.shouldPerformDownload || scheme == "blob" {
                decisionHandler(.download)
                return
            }


SWIFT;

$patched = str_replace($policyAnchor, $policyBranch.$policyAnchor, $patched);

$methodsAnchor = "        @objc func keyboardWillShow(_ notification: Notification) {\n";

if (! str_contains($patched, $methodsAnchor)) {
    fwrite(STDERR, "nativephp_ios_download_delegate: keyboard-observer anchor not found in {$target}.\n");
    fwrite(STDERR, "The generated shell changed shape; the download delegate has nowhere to live.\n");
    exit(1);
}

/*
 * Destinations are held per download rather than as one property: two saves
 * can be in flight, and the second would otherwise overwrite the first one's
 * path and hand the share sheet the wrong file.
 */
$methods = <<<'SWIFT'
        // Added by scripts/nativephp_ios_download_delegate.php — see that file
        // for why the generated shell needs it.
        private var downloadDestinations: [ObjectIdentifier: URL] = [:]

        func webView(_ webView: WKWebView,
                     navigationAction: WKNavigationAction,
                     didBecome download: WKDownload) {
            download.delegate = self
        }

        func webView(_ webView: WKWebView,
                     navigationResponse: WKNavigationResponse,
                     didBecome download: WKDownload) {
            download.delegate = self
        }

        func download(_ download: WKDownload,
                      decideDestinationUsing response: URLResponse,
                      suggestedFilename: String,
                      completionHandler: @escaping (URL?) -> Void) {
            let name = suggestedFilename.isEmpty ? "download" : suggestedFilename
            let directory = FileManager.default.temporaryDirectory
                .appendingPathComponent("beatrax-downloads", isDirectory: true)

            try? FileManager.default.createDirectory(at: directory, withIntermediateDirectories: true)

            let destination = directory.appendingPathComponent(name)

            // WKDownload refuses a destination that already exists, so a second
            // save of the same filename would fail rather than replace it.
            try? FileManager.default.removeItem(at: destination)

            self.downloadDestinations[ObjectIdentifier(download)] = destination
            completionHandler(destination)
        }

        func downloadDidFinish(_ download: WKDownload) {
            guard let destination = self.downloadDestinations.removeValue(forKey: ObjectIdentifier(download)) else {
                return
            }

            NSLog("%@", "[NativePHP] [DOWNLOAD] saved \(destination.lastPathComponent)")
            self.presentSaveSheet(for: destination)
        }

        func download(_ download: WKDownload, didFailWithError error: Error, resumeData: Data?) {
            self.downloadDestinations.removeValue(forKey: ObjectIdentifier(download))
            NSLog("%@", "[NativePHP] [DOWNLOAD] failed: \(error.localizedDescription)")
        }

        // The share sheet is the save: it is how a file leaves an app on iOS,
        // and "Save to Files" inside it is the destination a person means when
        // they tap Download. Presented from the topmost controller so it still
        // appears when a native screen is over the WebView.
        private func presentSaveSheet(for fileURL: URL) {
            DispatchQueue.main.async {
                guard let scene = UIApplication.shared.connectedScenes
                        .compactMap({ $0 as? UIWindowScene })
                        .first(where: { $0.activationState == .foregroundActive }),
                      let root = scene.windows.first(where: { $0.isKeyWindow })?.rootViewController else {
                    return
                }

                var presenter = root
                while let presented = presenter.presentedViewController {
                    presenter = presented
                }

                let sheet = UIActivityViewController(activityItems: [fileURL], applicationActivities: nil)
                sheet.popoverPresentationController?.sourceView = presenter.view
                sheet.popoverPresentationController?.sourceRect = CGRect(
                    x: presenter.view.bounds.midX,
                    y: presenter.view.bounds.midY,
                    width: 0,
                    height: 0
                )

                presenter.present(sheet, animated: true)
            }
        }


SWIFT;

$patched = str_replace($methodsAnchor, $methods.$methodsAnchor, $patched);

if (! str_contains($patched, 'downloadDidFinish')) {
    fwrite(STDERR, "nativephp_ios_download_delegate: patch produced no change in {$target}.\n");
    exit(1);
}

if (file_put_contents($target, $patched) === false) {
    fwrite(STDERR, "nativephp_ios_download_delegate: could not write {$target}.\n");
    exit(1);
}

fwrite(STDOUT, "nativephp_ios_download_delegate: downloads now save instead of replacing the app.\n");

exit(0);
