<?php

declare(strict_types=1);

/*
 * Open the Android document picker for `<input type="file">`.
 *
 * `native:install` generates a WebChromeClient that overrides
 * onShowCustomView/onHideCustomView/onConsoleMessage/onCreateWindow and
 * nothing else. Android's default `onShowFileChooser` returns false and shows
 * nothing at all — no picker, no error, no activity change — so every file
 * input in the app is inert on Android. Tapping one does nothing.
 *
 * That is not a cosmetic gap. `/` redirects to `/imports/new` while the device
 * holds no transactions, and every wizard drop-zone uses the same control, so
 * without this override a freshly installed phone cannot take in a statement
 * and cannot reach the dashboard by any route.
 *
 * The chooser is started with the intent the WebView itself builds
 * (`FileChooserParams.createIntent()`), so the accept-types and multiple
 * attributes declared in the page are honoured rather than re-derived here.
 * The result comes back through MainActivity, which is why this patches two
 * files: a WebChromeClient has no activity-result callback of its own.
 *
 * Every path settles the callback exactly once. An unsettled
 * ValueCallback leaves the WebView believing a chooser is still open and it
 * refuses to raise another for the lifetime of the page — one dropped callback
 * disables file input everywhere until the app restarts.
 *
 * The generated tree is regenerated by `native:install`, which composer's
 * post-update-cmd re-runs, so this patch is applied from there rather than
 * hand-edited. It is idempotent: a second run over an already-patched file is
 * a no-op, and a missing anchor is a hard failure rather than a silent skip,
 * because a silently unpatched shell degrades to exactly the behaviour this
 * exists to fix.
 */

$root = __DIR__.'/../mobile-app/nativephp/android/app/src/main/java/com/nativephp/mobile';

$webViewTarget = $root.'/network/WebViewManager.kt';
$activityTarget = $root.'/ui/MainActivity.kt';

if (! is_file($webViewTarget)) {
    // The native scaffold is generated on demand and is absent from a fresh
    // checkout; there is nothing to patch until `native:install` has run.
    fwrite(STDOUT, "nativephp_android_file_chooser: no Android scaffold yet — skipping.\n");
    exit(0);
}

/*
 * The holder is a top-level object rather than state on the chrome client: the
 * client is recreated per WebView, and the activity result arrives after the
 * chooser activity has been on top, by which point the instance that started
 * it may be gone.
 */
$holder = <<<'KOTLIN'

/*
 * Added by scripts/nativephp_android_file_chooser.php — see that file for why
 * the generated shell needs it.
 *
 * Bridges a WebChromeClient file-chooser request to an activity result, which
 * only MainActivity can receive.
 */
object BeatraxFileChooser {
    const val REQUEST_CODE = 9201

    private var pending: ValueCallback<Array<Uri>>? = null

    /** Replaces any in-flight request, settling the old one so it cannot hang. */
    fun start(callback: ValueCallback<Array<Uri>>?) {
        pending?.onReceiveValue(null)
        pending = callback
    }

    /** Settles the in-flight request with nothing. Safe to call when idle. */
    fun cancel() {
        pending?.onReceiveValue(null)
        pending = null
    }

    fun deliver(resultCode: Int, data: Intent?) {
        val callback = pending ?: return
        pending = null

        // parseResult yields null for a cancelled chooser, which is precisely
        // what the page should observe: the input keeps its previous value.
        callback.onReceiveValue(
            WebChromeClient.FileChooserParams.parseResult(resultCode, data)
        )
    }
}
KOTLIN;

$override = <<<'KOTLIN'
return object : WebChromeClient() {
            // Added by scripts/nativephp_android_file_chooser.php — see that
            // file for why the generated shell needs it.
            override fun onShowFileChooser(
                webView: WebView?,
                filePathCallback: ValueCallback<Array<Uri>>?,
                fileChooserParams: FileChooserParams?
            ): Boolean {
                val activity = context as? Activity
                val intent = fileChooserParams?.createIntent()

                // Returning false tells the WebView to fall back to its default
                // handling, which is to do nothing — so settle the callback
                // first rather than leaving the page waiting on a chooser that
                // will never open.
                if (activity == null || intent == null) {
                    Log.i(TAG, "onShowFileChooser: no activity or intent — declining")
                    filePathCallback?.onReceiveValue(null)
                    return false
                }

                BeatraxFileChooser.start(filePathCallback)

                return try {
                    activity.startActivityForResult(intent, BeatraxFileChooser.REQUEST_CODE)
                    true
                } catch (e: ActivityNotFoundException) {
                    // No document provider on the device. Settle the callback
                    // so the input is merely empty rather than permanently
                    // wedged, and tell the user why nothing opened.
                    Log.w(TAG, "onShowFileChooser: no activity to handle the chooser", e)
                    BeatraxFileChooser.cancel()
                    Toast.makeText(activity, "No app available to pick a file.", Toast.LENGTH_LONG).show()
                    false
                }
            }

KOTLIN;

$webViewSource = (string) file_get_contents($webViewTarget);

if (str_contains($webViewSource, 'onShowFileChooser')) {
    fwrite(STDOUT, "nativephp_android_file_chooser: WebViewManager already patched.\n");
} else {
    $anchor = "return object : WebChromeClient() {\n";

    if (! str_contains($webViewSource, $anchor)) {
        fwrite(STDERR, "nativephp_android_file_chooser: WebChromeClient anchor not found in {$webViewTarget}.\n");
        fwrite(STDERR, "The generated shell changed shape; re-check the override before shipping a build.\n");
        exit(1);
    }

    $patched = str_replace($anchor, $override, $webViewSource);

    if (! str_contains($patched, 'object BeatraxFileChooser')) {
        $patched = rtrim($patched, "\n")."\n".$holder;
    }

    if (file_put_contents($webViewTarget, $patched) === false) {
        fwrite(STDERR, "nativephp_android_file_chooser: could not write {$webViewTarget}.\n");
        exit(1);
    }

    fwrite(STDOUT, "nativephp_android_file_chooser: WebView now opens the document picker.\n");
}

/*
 * The result half. A WebChromeClient cannot receive an activity result, so
 * MainActivity forwards the one request code this owns and leaves every other
 * result to the existing handlers.
 */
if (! is_file($activityTarget)) {
    fwrite(STDERR, "nativephp_android_file_chooser: {$activityTarget} not found.\n");
    fwrite(STDERR, "The chooser opens but its result cannot be delivered; the file input would hang.\n");
    exit(1);
}

$activitySource = (string) file_get_contents($activityTarget);

if (str_contains($activitySource, 'BeatraxFileChooser.deliver')) {
    fwrite(STDOUT, "nativephp_android_file_chooser: MainActivity already forwards the result.\n");
    exit(0);
}

$activityAnchor = "    override fun onRequestPermissionsResult(\n";

if (! str_contains($activitySource, $activityAnchor)) {
    fwrite(STDERR, "nativephp_android_file_chooser: onRequestPermissionsResult anchor not found in {$activityTarget}.\n");
    fwrite(STDERR, "The generated activity changed shape; re-check the override before shipping a build.\n");
    exit(1);
}

$activityOverride = <<<'KOTLIN'
    // Added by scripts/nativephp_android_file_chooser.php — the chrome client
    // starts the document picker but has no way to hear the answer.
    override fun onActivityResult(requestCode: Int, resultCode: Int, data: Intent?) {
        super.onActivityResult(requestCode, resultCode, data)

        if (requestCode == com.nativephp.mobile.network.BeatraxFileChooser.REQUEST_CODE) {
            com.nativephp.mobile.network.BeatraxFileChooser.deliver(resultCode, data)
        }
    }

KOTLIN;

$activityPatched = str_replace($activityAnchor, $activityOverride.$activityAnchor, $activitySource);

if (file_put_contents($activityTarget, $activityPatched) === false) {
    fwrite(STDERR, "nativephp_android_file_chooser: could not write {$activityTarget}.\n");
    exit(1);
}

fwrite(STDOUT, "nativephp_android_file_chooser: MainActivity now delivers the chooser result.\n");

exit(0);
