#!/usr/bin/env php
<?php

declare(strict_types=1);

/**
 * Ensures the NativePHP electron package.json's `imports` map exposes the
 * `#plugin/*` subpath in addition to the bare `#plugin` entry.
 *
 * Runs as a `prebuild` hook (see config/nativephp.php).
 *
 * Why this is needed:
 *
 *   The electron main process imports specific submodules of the bundled
 *   NativePHP electron-plugin — for example `#plugin/server/state.js` — to
 *   reach the Laravel-side state shared by NativePHP's own handlers. The
 *   NativePHP-published package.json only declares the bare `#plugin`
 *   specifier, so `#plugin/server/*` fails to resolve under Node subpath
 *   imports and the Vite / Rollup build aborts with
 *
 *     [commonjs--resolver] Missing "#plugin/server/state.js" specifier in
 *     "beatrax" package
 *
 *   `nativephp/` is gitignored (regenerated by `native:install --publish`),
 *   so the patch must be re-applied every build.
 *
 * The hook is idempotent — it is safe to run on every build.
 *
 * Exit codes:
 *   0  imports map already complete, or successfully patched
 *   1  the electron working directory or its package.json is missing
 */
$projectRoot = dirname(__DIR__);
$pkgPath = $projectRoot.'/nativephp/electron/package.json';

if (! is_file($pkgPath)) {
    fwrite(STDERR, "nativephp_patch_electron_imports: {$pkgPath} not found — run `php artisan native:install --publish` first.\n");

    exit(1);
}

$raw = file_get_contents($pkgPath);
$pkg = json_decode($raw, true);

if (! is_array($pkg)) {
    fwrite(STDERR, "nativephp_patch_electron_imports: could not parse {$pkgPath} as JSON.\n");

    exit(1);
}

$imports = $pkg['imports'] ?? [];

if (! is_array($imports)) {
    $imports = [];
}

$desired = './electron-plugin/dist/*';

if (($imports['#plugin/*'] ?? null) === $desired) {
    fwrite(STDOUT, "nativephp_patch_electron_imports: imports map already has #plugin/* entry — skipping.\n");

    exit(0);
}

$imports['#plugin/*'] = $desired;
$pkg['imports'] = $imports;

$encoded = json_encode($pkg, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES);

if ($encoded === false) {
    fwrite(STDERR, "nativephp_patch_electron_imports: failed to encode patched package.json.\n");

    exit(1);
}

if (file_put_contents($pkgPath, $encoded."\n") === false) {
    fwrite(STDERR, "nativephp_patch_electron_imports: failed to write {$pkgPath}\n");

    exit(1);
}

fwrite(STDOUT, "nativephp_patch_electron_imports: added #plugin/* → {$desired} to imports map.\n");

exit(0);
