#!/usr/bin/env php
<?php

declare(strict_types=1);

/**
 * Extends the OS file-open ingress to Windows and Linux.
 *
 * Why this is needed:
 *
 *   NativePHP's Electron plugin forwards macOS `app.on('open-file')` to
 *   `Native\Desktop\Events\App\OpenFile`, which is the event
 *   `HandleNativeOpenFile` subscribes to. Windows and Linux never emit
 *   `open-file`: they hand the document path to the process on `process.argv`
 *   at cold start, and to the already-running instance through
 *   `app.on('second-instance')`. NativePHP registers a `second-instance`
 *   handler only when a deep-link scheme is configured, and forwards it as
 *   `OpenedFromURL` — a deep link, not a document. So on those two platforms
 *   a double-clicked export opened the app onto the dashboard, and a second
 *   double-click opened a second copy of the app.
 *
 *   Both paths are forwarded here through NativePHP's own
 *   `notifyLaravel('events', …)` transport, which already authenticates
 *   itself with `X-NativePHP-Secret` against the loopback PHP server. That
 *   keeps ONE PHP-side subscriber and adds no HTTP route of Beatrax's own —
 *   a route in the `web` group could only ever answer 419 to a main-process
 *   POST that carries no session and no token.
 *
 *   `nativephp/` is gitignored and regenerated by `native:install --publish`,
 *   so this runs as a `prebuild` hook rather than as a committed edit.
 *
 * The hook is idempotent: a main process already carrying the marker is left
 * untouched.
 *
 * Exit codes:
 *   0  patched, or already correct
 *   1  the electron main process source could not be located or patched
 */
/**
 * Marker comment written into the patched file; its presence is the
 * idempotency check.
 */
const FILE_OPEN_INGRESS_MARKER = '// -- Beatrax OS file-open ingress --';

/**
 * The published NativePHP bootstrap call, spliced in after. Verbatim on
 * purpose: a release that reshapes it must fail this hook loudly rather than
 * leave a main process that silently drops every document path.
 */
const FILE_OPEN_INGRESS_ANCHOR = 'NativePHP.bootstrap(app, defaultIcon, phpBinary, certificate, appPath);';

$isDirectlyInvoked = PHP_SAPI === 'cli'
    && isset($_SERVER['argv'][0])
    && realpath((string) $_SERVER['argv'][0]) === __FILE__;

if ($isDirectlyInvoked) {
    $indexJsPath = dirname(__DIR__).'/nativephp/electron/src/main/index.js';

    if (! is_file($indexJsPath)) {
        fwrite(STDERR, "nativephp_inject_file_open_ingress: {$indexJsPath} not found — run `php artisan native:install --publish` first.\n");

        exit(1);
    }

    $source = file_get_contents($indexJsPath);

    if ($source === false) {
        fwrite(STDERR, "nativephp_inject_file_open_ingress: could not read {$indexJsPath}\n");

        exit(1);
    }

    [$patched, $reason] = injectFileOpenIngress($source);

    if ($patched === null) {
        fwrite(STDERR, "nativephp_inject_file_open_ingress: {$reason}\n");

        exit(1);
    }

    if ($patched === $source) {
        fwrite(STDOUT, "nativephp_inject_file_open_ingress: index.js already wired — skipping.\n");

        exit(0);
    }

    if (file_put_contents($indexJsPath, $patched) === false) {
        fwrite(STDERR, "nativephp_inject_file_open_ingress: could not write {$indexJsPath}\n");

        exit(1);
    }

    fwrite(STDOUT, "nativephp_inject_file_open_ingress: wired argv + second-instance file-open into {$indexJsPath}.\n");

    exit(0);
}

/**
 * @return array{0: string|null, 1: string} [patched source or null on failure, human-readable status]
 */
function injectFileOpenIngress(string $source): array
{
    if (str_contains($source, FILE_OPEN_INGRESS_MARKER)) {
        return [$source, 'already-patched'];
    }

    $at = strpos($source, FILE_OPEN_INGRESS_ANCHOR);

    if ($at === false) {
        return [null, 'could not locate the `NativePHP.bootstrap(app, defaultIcon, phpBinary, certificate, appPath);` call site'];
    }

    $after = $at + strlen(FILE_OPEN_INGRESS_ANCHOR);

    $patched = substr($source, 0, $after)."\n\n".fileOpenIngressBlock()."\n".substr($source, $after);

    return [$patched, 'patched'];
}

/**
 * The extensions argv is scanned for. This only decides which argument is a
 * document rather than a flag — canonicalising the path, rejecting a
 * directory or a non-file and enforcing the size cap all stay on the PHP side
 * in `FileOpenIntake`, which is the security boundary either entry path
 * converges on.
 *
 * @return list<string>
 */
function fileOpenIngressExtensions(): array
{
    return ['csv', 'eml'];
}

function fileOpenIngressBlock(): string
{
    $marker = FILE_OPEN_INGRESS_MARKER;
    $extensions = implode(', ', array_map(
        static fn (string $ext): string => "'.".$ext."'",
        fileOpenIngressExtensions(),
    ));

    return <<<JS
    {$marker}
    // macOS gets its document path from app.on('open-file'), which the
    // NativePHP plugin already forwards. Windows and Linux never emit it:
    // the path arrives on argv, and on a second launch only through
    // 'second-instance' — which needs the lock NativePHP takes only for
    // deep links.
    const BEATRAX_FILE_OPEN_EXTENSIONS = [{$extensions}];
    const BEATRAX_FILE_OPEN_BOOT_ATTEMPTS = 100;
    const BEATRAX_FILE_OPEN_BOOT_INTERVAL_MS = 100;

    function beatraxDocumentFromArgv(argv) {
        if (!Array.isArray(argv)) {
            return null;
        }

        // Last-first: Electron puts its own flags ahead of the document, and
        // the shell appends the path the user acted on.
        for (let i = argv.length - 1; i >= 1; i--) {
            const candidate = argv[i];

            if (typeof candidate !== 'string' || candidate.startsWith('-')) {
                continue;
            }

            const lowered = candidate.toLowerCase();

            if (BEATRAX_FILE_OPEN_EXTENSIONS.some((ext) => lowered.endsWith(ext))) {
                return candidate;
            }
        }

        return null;
    }

    async function beatraxForwardDocument(documentPath) {
        // The PHP server binds its port during bootstrap, so a cold-start post
        // would go to a port nothing is listening on and notifyLaravel's own
        // catch would swallow it without a trace.
        const NativePHPState = (await import('#plugin/server/state.js')).default;
        const { notifyLaravel } = await import('#plugin/server/utils.js');

        for (let attempt = 0; attempt < BEATRAX_FILE_OPEN_BOOT_ATTEMPTS; attempt++) {
            if (NativePHPState.phpPort) {
                await notifyLaravel('events', {
                    event: '\\\\Native\\\\Desktop\\\\Events\\\\App\\\\OpenFile',
                    payload: [documentPath],
                });

                return;
            }

            await new Promise((resolve) => setTimeout(resolve, BEATRAX_FILE_OPEN_BOOT_INTERVAL_MS));
        }
    }

    async function beatraxFocusMainWindow() {
        const NativePHPState = (await import('#plugin/server/state.js')).default;
        const mainWindow = NativePHPState.windows?.main;

        if (!mainWindow) {
            return;
        }

        if (mainWindow.isMinimized()) {
            mainWindow.restore();
        }

        mainWindow.show();
        mainWindow.focus();
    }

    if (!app.requestSingleInstanceLock()) {
        // A second launch exists only to hand its argv to the instance that
        // holds the lock; two running copies of a ledger app is the bug.
        app.quit();
    } else {
        app.on('second-instance', (event, argv) => {
            beatraxFocusMainWindow();

            const reopened = beatraxDocumentFromArgv(argv);

            if (reopened) {
                beatraxForwardDocument(reopened);
            }
        });

        const coldStartDocument = beatraxDocumentFromArgv(process.argv);

        if (coldStartDocument) {
            beatraxForwardDocument(coldStartDocument);
        }
    }
    JS;
}
