#!/usr/bin/env php
<?php

declare(strict_types=1);

/**
 * Stages committed build inputs into the NativePHP / electron-builder
 * `buildResources` directory before each desktop build.
 *
 * Runs as a `prebuild` hook (see config/nativephp.php).
 *
 * Why this is needed:
 *
 *   The canonical home for platform icons in this repo is `public/icon.*`
 *   (the in-repo brand surface — PROJECT.md D-17/D-18). The macOS Hardened
 *   Runtime entitlements file lives at `build/entitlements.mac.plist`.
 *   electron-builder's `buildResources` directory (`nativephp/electron/build`)
 *   is the location it expects to discover `icon.icns`, `icon.ico`,
 *   `icon.png`, and `entitlements.mac.plist` — but the `nativephp/`
 *   directory is gitignored (regenerated by `native:install --publish`),
 *   so the committed source-of-truth files must be staged into it on every
 *   build.
 *
 * The hook copies:
 *
 *   public/icon.png             → nativephp/electron/build/icon.png
 *   public/icon.icns            → nativephp/electron/build/icon.icns
 *   public/icon.ico             → nativephp/electron/build/icon.ico
 *   build/entitlements.mac.plist → nativephp/electron/build/entitlements.mac.plist
 *
 * The hook is idempotent: it overwrites the staged copies on every run.
 * Files absent from the project root are skipped with a warning so a
 * partial brand-asset state still produces a build (the warning surfaces
 * which artefact is missing).
 *
 * Exit codes:
 *   0  staged (or nothing to do)
 *   1  the electron working directory does not exist
 */
$projectRoot = dirname(__DIR__);
$publishedDir = $projectRoot.'/nativephp/electron';

if (! is_dir($publishedDir)) {
    fwrite(STDERR, "nativephp_stage_build_resources: {$publishedDir} does not exist — run `php artisan native:install --publish` first.\n");

    exit(1);
}

$buildDir = $publishedDir.'/build';

if (! is_dir($buildDir) && ! mkdir($buildDir, 0755, true) && ! is_dir($buildDir)) {
    fwrite(STDERR, "nativephp_stage_build_resources: could not create {$buildDir}\n");

    exit(1);
}

$copies = [
    $projectRoot.'/public/icon.png' => $buildDir.'/icon.png',
    $projectRoot.'/public/icon.icns' => $buildDir.'/icon.icns',
    $projectRoot.'/public/icon.ico' => $buildDir.'/icon.ico',
    $projectRoot.'/build/entitlements.mac.plist' => $buildDir.'/entitlements.mac.plist',
];

foreach ($copies as $from => $to) {
    if (! is_file($from)) {
        fwrite(STDERR, "nativephp_stage_build_resources: skipping (missing) {$from}\n");

        continue;
    }

    if (! copy($from, $to)) {
        fwrite(STDERR, "nativephp_stage_build_resources: failed copying {$from} → {$to}\n");

        exit(1);
    }

    fwrite(STDOUT, 'nativephp_stage_build_resources: staged '.basename($from)."\n");
}

exit(0);
