<?php

declare(strict_types=1);

/*
 * Let a multipart upload body reach PHP on iOS.
 *
 * The generated scheme handler reads `request.httpBody` and nothing else.
 * WebKit only populates that property for simple string bodies; a FormData or
 * Blob body — which is every file upload — arrives as `httpBodyStream`
 * instead, and the handler dropped it without a word. PHP then saw a POST
 * carrying a `multipart/form-data` Content-Type with its boundary, a null
 * CONTENT_LENGTH, and a zero-byte `php://input`, so `$_FILES` and `$_POST`
 * were both empty.
 *
 * Measured on the device before this patch, posting a FormData to a probe
 * route: `php_input_bytes: 0`, `FILES_keys: []`, while the same probe posting
 * `application/json` or `application/x-www-form-urlencoded` arrived intact.
 * That asymmetry is exactly the httpBody / httpBodyStream split, and it is why
 * every ordinary Livewire round trip worked while no upload ever could.
 *
 * READ THIS BEFORE ASSUMING IT IS WHAT MAKES UPLOADS WORK: on its own, today,
 * this patch buys nothing. WebKit hands a custom scheme handler neither
 * `httpBody` NOR `httpBodyStream` for a FormData body — measured after this
 * patch shipped, a FormData POST still reached PHP as zero bytes. File uploads
 * work because the client encodes them into a JSON string body instead
 * (`resources/js/mobile-upload.js`, `EncodedUploadTransport`), which is a
 * transport that does not depend on this at all.
 *
 * It is kept because it is correct and becomes load-bearing the moment a body
 * does arrive as a stream — a WebKit fix, a different body shape, or a future
 * shell that forwards one. It costs a nil check on a path that already runs.
 *
 * The body still crosses into PHP as a UTF-8 string, which this patch does not
 * change: `RequestData.data` is typed `String?` all the way through the
 * generated shell. A body that is not valid UTF-8 is left decoding to nil
 * rather than being silently mangled — which is also why the base64 transport,
 * being ASCII, is what carries a PDF.
 *
 * The generated tree is regenerated by `native:install`, so this is applied
 * from composer's hooks rather than hand-edited. It is idempotent, and a
 * missing anchor is a hard failure rather than a silent skip, because an
 * unpatched shell degrades to exactly the behaviour this exists to fix.
 */

$target = __DIR__.'/../mobile-app/nativephp/ios/NativePHP/PHPSchemeHandler.swift';

if (! is_file($target)) {
    // The native scaffold is generated on demand and is absent from a fresh
    // checkout; there is nothing to patch until `native:install` has run.
    fwrite(STDOUT, "nativephp_ios_request_body_stream: no iOS scaffold yet — skipping.\n");
    exit(0);
}

$source = (string) file_get_contents($target);

if (str_contains($source, 'drainBodyStream')) {
    fwrite(STDOUT, "nativephp_ios_request_body_stream: already patched.\n");
    exit(0);
}

$anchor = <<<'SWIFT'
        // Extract POST data if method is POST/PUT/PATCH
        var data: String?
        if ["POST", "PUT", "PATCH"].contains(method.uppercased()), let httpBody = request.httpBody {
            if let body = String(data: httpBody, encoding: .utf8) {
                data = body
            }
        }
SWIFT;

if (! str_contains($source, $anchor)) {
    fwrite(STDERR, "nativephp_ios_request_body_stream: request-body anchor not found in {$target}.\n");
    fwrite(STDERR, "The generated handler changed shape; re-check the body extraction before shipping a build.\n");
    exit(1);
}

$replacement = <<<'SWIFT'
        // Extract POST data if method is POST/PUT/PATCH.
        //
        // Patched by scripts/nativephp_ios_request_body_stream.php — WebKit
        // hands a custom scheme handler `httpBody` only for simple string
        // bodies. A FormData or Blob body arrives as `httpBodyStream`, and
        // reading only the former dropped every file upload silently.
        var data: String?
        if ["POST", "PUT", "PATCH"].contains(method.uppercased()) {
            var bodyData = request.httpBody

            if bodyData == nil, let bodyStream = request.httpBodyStream {
                bodyData = PHPSchemeHandler.drainBodyStream(bodyStream)
            }

            if let bodyData, let body = String(data: bodyData, encoding: .utf8) {
                data = body
            }
        }
SWIFT;

$patched = str_replace($anchor, $replacement, $source);

$helperAnchor = "    private func parseSetCookieHeader(cookieString: String) -> [HTTPCookiePropertyKey: Any] {\n";

if (! str_contains($patched, $helperAnchor)) {
    fwrite(STDERR, "nativephp_ios_request_body_stream: parseSetCookieHeader anchor not found in {$target}.\n");
    fwrite(STDERR, "The generated handler changed shape; the stream reader has nowhere to live.\n");
    exit(1);
}

/*
 * Static because the drain needs no handler state, and a scheme task can be
 * served from whichever instance WebKit hands the request to.
 */
$helper = <<<'SWIFT'
    // Added by scripts/nativephp_ios_request_body_stream.php — see that file
    // for why the generated shell needs it.
    //
    // Returns nil when the stream reports an error, so a half-read body is
    // never handed onward as if it were whole.
    static func drainBodyStream(_ stream: InputStream) -> Data? {
        stream.open()
        defer { stream.close() }

        let bufferSize = 64 * 1024
        var buffer = [UInt8](repeating: 0, count: bufferSize)
        var collected = Data()

        while stream.hasBytesAvailable {
            let read = stream.read(&buffer, maxLength: bufferSize)

            if read < 0 {
                return nil
            }

            if read == 0 {
                break
            }

            collected.append(buffer, count: read)
        }

        return collected
    }


SWIFT;

$patched = str_replace($helperAnchor, $helper.$helperAnchor, $patched);

if (! str_contains($patched, 'drainBodyStream')) {
    fwrite(STDERR, "nativephp_ios_request_body_stream: patch produced no change in {$target}.\n");
    exit(1);
}

if (file_put_contents($target, $patched) === false) {
    fwrite(STDERR, "nativephp_ios_request_body_stream: could not write {$target}.\n");
    exit(1);
}

fwrite(STDOUT, "nativephp_ios_request_body_stream: multipart upload bodies now reach PHP.\n");

exit(0);
