<?php

declare(strict_types=1);

/*
 * Grant the Android WebView's camera permission requests.
 *
 * `native:install` generates `WebViewManager.kt` with a WebChromeClient that
 * overrides onShowCustomView/onHideCustomView and nothing else. Without an
 * `onPermissionRequest` override, Android WebView neither grants nor denies a
 * getUserMedia() call — the promise simply never settles — so an in-page
 * camera preview is impossible and the only scan surface left is the
 * scanner plugin's separate full-screen activity.
 *
 * The app already holds the OS-level CAMERA permission (declared in the
 * generated manifest and granted at runtime by the scanner flow), so the
 * override only forwards a decision the user has already made. Video capture
 * is the sole resource admitted; anything else is denied rather than passed
 * through, so this cannot become a blanket grant for the microphone or
 * protected media.
 *
 * The generated tree is regenerated by `native:install`, which composer's
 * post-update-cmd re-runs, so this patch is applied from there rather than
 * hand-edited. It is idempotent: a second run over an already-patched file is
 * a no-op, and a missing anchor is a hard failure rather than a silent skip,
 * because a silently unpatched shell degrades to exactly the behaviour this
 * exists to fix.
 */

$target = __DIR__.'/../mobile-app/nativephp/android/app/src/main/java/com/nativephp/mobile/network/WebViewManager.kt';

if (! is_file($target)) {
    // The native scaffold is generated on demand and is absent from a fresh
    // checkout; there is nothing to patch until `native:install` has run.
    fwrite(STDOUT, "nativephp_grant_webview_camera: no Android scaffold yet — skipping.\n");
    exit(0);
}

$source = (string) file_get_contents($target);

$marker = 'onPermissionRequest';
if (str_contains($source, $marker)) {
    fwrite(STDOUT, "nativephp_grant_webview_camera: already patched.\n");
    exit(0);
}

$anchor = "return object : WebChromeClient() {\n";
if (! str_contains($source, $anchor)) {
    fwrite(STDERR, "nativephp_grant_webview_camera: WebChromeClient anchor not found in {$target}.\n");
    fwrite(STDERR, "The generated shell changed shape; re-check the override before shipping a build.\n");
    exit(1);
}

$override = <<<'KOTLIN'
return object : WebChromeClient() {
            // Added by scripts/nativephp_grant_webview_camera.php — see that
            // file for why the generated shell needs it.
            override fun onPermissionRequest(request: PermissionRequest) {
                val video = request.resources
                    .filter { it == PermissionRequest.RESOURCE_VIDEO_CAPTURE }
                    .toTypedArray()

                if (video.isEmpty()) {
                    request.deny()
                    return
                }

                val activity = context as? Activity
                if (activity != null) {
                    activity.runOnUiThread { request.grant(video) }
                } else {
                    request.grant(video)
                }
            }

KOTLIN;

$patched = str_replace($anchor, $override, $source);

if (file_put_contents($target, $patched) === false) {
    fwrite(STDERR, "nativephp_grant_webview_camera: could not write {$target}.\n");
    exit(1);
}

fwrite(STDOUT, "nativephp_grant_webview_camera: granted WebView video capture.\n");
exit(0);
